unit TestUfItem;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Vcl.Grids, ppParameter, ppCtrls, ppPrnabl, ppBands, System.SysUtils,
  Vcl.Graphics, System.Classes, uControle, Data.Win.ADODB, Winapi.Messages, ppReport,
  Vcl.ExtCtrls, ppDB, ppRelatv, Vcl.Controls, Vcl.Imaging.pngimage, Vcl.Dialogs,
  Vcl.DBGrids, ppDBPipe, Data.DB, ppProd, ppComm, ppDesignLayer, System.Variants, ppCache,
  ppClass, Vcl.Forms, Data.DBXMSSQL, Winapi.Windows, UItem, UfItem, Data.SqlExpr,
  Vcl.StdCtrls, ppVar;

type
  // Test methods for class TFrmItem

  TestTFrmItem = class(TTestCase)
  strict private
    FFrmItem: TFrmItem;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestbtnFecharClick;
    procedure TestbtnAtualizaGridClick;
    procedure TestbtnNovoClick;
    procedure TestbtnAlterarClick;
    procedure TestbtnDeletarClick;
    procedure TestbtnSalvarClick;
    procedure TestbtnImprimirClick;
  end;

implementation

procedure TestTFrmItem.SetUp;
begin
  FFrmItem := TFrmItem.Create;
end;

procedure TestTFrmItem.TearDown;
begin
  FFrmItem.Free;
  FFrmItem := nil;
end;

procedure TestTFrmItem.TestbtnFecharClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FFrmItem.btnFecharClick(Sender);
  // TODO: Validate method results
end;

procedure TestTFrmItem.TestbtnAtualizaGridClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FFrmItem.btnAtualizaGridClick(Sender);
  // TODO: Validate method results
end;

procedure TestTFrmItem.TestbtnNovoClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FFrmItem.btnNovoClick(Sender);
  // TODO: Validate method results
end;

procedure TestTFrmItem.TestbtnAlterarClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FFrmItem.btnAlterarClick(Sender);
  // TODO: Validate method results
end;

procedure TestTFrmItem.TestbtnDeletarClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FFrmItem.btnDeletarClick(Sender);
  // TODO: Validate method results
end;

procedure TestTFrmItem.TestbtnSalvarClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FFrmItem.btnSalvarClick(Sender);
  // TODO: Validate method results
end;

procedure TestTFrmItem.TestbtnImprimirClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FFrmItem.btnImprimirClick(Sender);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTFrmItem.Suite);
end.

