unit TestUfCategoria;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Vcl.Grids, ppParameter, ppCtrls, ppPrnabl, ppBands, System.SysUtils,
  Vcl.Graphics, System.Classes, uControle, Data.Win.ADODB, Winapi.Messages, ppReport,
  Vcl.ExtCtrls, ppDB, ppRelatv, Vcl.Controls, Vcl.Imaging.pngimage, Vcl.Dialogs, ppDBPipe,
  Data.DB, ppProd, ppComm, ppDesignLayer, System.Variants, ppCache, ppClass, Vcl.Forms,
  Winapi.Windows, Vcl.DBGrids, Vcl.Imaging.jpeg, Vcl.StdCtrls, ppVar, Ucategoria,
  UfCategoria;

type
  // Test methods for class TFrmCategoria

  TestTFrmCategoria = class(TTestCase)
  strict private
    FFrmCategoria: TFrmCategoria;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestbtnSalvarClick;
    procedure TestbtnAtualizaGridClick;
    procedure TestbtnAlterarClick;
    procedure TestbtnDeletarClick;
    procedure TestFormShow;
    procedure TestbtnFecharClick;
    procedure TestbtnNovoClick;
    procedure TestbtnImprimirClick;
  end;

implementation

procedure TestTFrmCategoria.SetUp;
begin
  FFrmCategoria := TFrmCategoria.Create;
end;

procedure TestTFrmCategoria.TearDown;
begin
  FFrmCategoria.Free;
  FFrmCategoria := nil;
end;

procedure TestTFrmCategoria.TestbtnSalvarClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FFrmCategoria.btnSalvarClick(Sender);
  // TODO: Validate method results
end;

procedure TestTFrmCategoria.TestbtnAtualizaGridClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FFrmCategoria.btnAtualizaGridClick(Sender);
  // TODO: Validate method results
end;

procedure TestTFrmCategoria.TestbtnAlterarClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FFrmCategoria.btnAlterarClick(Sender);
  // TODO: Validate method results
end;

procedure TestTFrmCategoria.TestbtnDeletarClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FFrmCategoria.btnDeletarClick(Sender);
  // TODO: Validate method results
end;

procedure TestTFrmCategoria.TestFormShow;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FFrmCategoria.FormShow(Sender);
  // TODO: Validate method results
end;

procedure TestTFrmCategoria.TestbtnFecharClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FFrmCategoria.btnFecharClick(Sender);
  // TODO: Validate method results
end;

procedure TestTFrmCategoria.TestbtnNovoClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FFrmCategoria.btnNovoClick(Sender);
  // TODO: Validate method results
end;

procedure TestTFrmCategoria.TestbtnImprimirClick;
var
  Sender: TObject;
begin
  // TODO: Setup method call parameters
  FFrmCategoria.btnImprimirClick(Sender);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTFrmCategoria.Suite);
end.

